#+TITLE: Tanki

[[logo][file:https://github.com/pkulev/tanki/blob/main/images/logo.png]]

Submission for [[https://itch.io/jam/autumn-lisp-game-jam-2021][itch.io]] Autumn Lisp Game Jam
Little Flappy Birds inspired game made using =hy= lisp, beautiful =raylib= and my bad gamedev skills.

* Installation

** Development
   Requires =poetry=, raylib and python3.9+.
   #+begin_src bash
     # clone the sources
     git clone git@github.com:pkulev/tanki.git && cd tanki
     # install poetry 1.2.0+
     curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 - --preview
     # set venv to be in the project root
     poetry config virtualenvs.in-project true
     # create venv and install project
     poetry install
     # run
     poetry run tanki
     # do this if you want to use `poetry exec`
     poetry plugin add poetry-exec-plugin
   #+end_src

* Build
** Pyinstaller
   Requires =poetry-exec-plugin= (see [[*Development][Development]] section)
   #+begin_src bash
     poetry exec pyinstaller
     # run build
     poetry exec tanki
   #+end_src
* Controls
  |---------+---------------|
  | Binding | Action        |
  |---------+---------------|
  | LSHIFT  | jump engine   |
  | SPACE   | Alpha strike  |
  | ESCAPE  | Exit game     |
  | P       | Toggle pause  |
  | D       | Toggle debug  |
  | R       | Restart level |
  | M       | Toggle music  |
  |---------+---------------|

* Assets
  - Graphics
    Made in Krita.
  - Music
    Made in [[https://www.beepbox.co][BeepBox]]
  - Sounds
    - Thunder :: [[https://freesound.org/people/Fission9/sounds/581124/][freesound]] ([[https://creativecommons.org/publicdomain/zero/1.0/][Creative Commons 0 License]])
    - Jetpack :: [[https://freesound.org/people/thatjeffcarter/sounds/128075/][freesound]] ([[https://creativecommons.org/licenses/by/3.0/][Attribution License]])
      I've deleted initial ignition part, modified sound is =jetpack-cut.wav=.
    - Rain :: [[https://freesound.org/people/InspectorJ/sounds/400402/][freesound]] ([[https://creativecommons.org/licenses/by/3.0/][Attribution License]])

    Other sounds generated in Bfxr.

* Screenshots

  [[paused][file:https://github.com/pkulev/tanki/blob/main/images/screenshot1.png]]
  [[new score][file:https://github.com/pkulev/tanki/blob/main/images/screenshot2.png]]

* Known bugs
** While holding =jump engine= button long enough sound restarts with hearable gap.
   Maybe new function in =raylib= (=SeekMusicStream=) will fix this, but I can't use it in my version.
   This behaviour is very unlikely to show up, because obstacles are close to each other and I restart
   jetpack sound on =jump engine= key released when it is close to end.
