name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: uv sync --all-extras

      - name: build for linux
        run: uv run poe build-linux

      # - name: make archive
      #   run: |
      #     pushd build/linux
      #     tar cvfz tanki-linux.tar.gz thetanki
      #     ls -lah tanki-linux.tar.gz
      #     popd

      - name: rename out dir
        run: mv build/linux/thetanki build/linux/tanki-linux

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: tanki-linux-${{ github.sha }}.tar.gz
      #     path: build/linux/tanki-linux.tar.gz

      - name: upload release to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: linux
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip && chmod +x butler
          ./butler push build/linux pkulev/tanki:${CHANNEL}

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: uv sync --all-extras

      - name: build for windows
        run: uv run poe build-windows

      # - name: make archive
      #   run: |
      #     pushd build/windows
      #     tar cvfz tanki-windows.tar.gz
      #     ls -lah tanki-windows.tar.gz
      #     popd

      - name: rename out dir
        run: mv build/windows/thetanki build/windows/tanki-windows

      - name: upload release to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
          Expand-Archive butler.zip .
          ./butler push build/windows pkulev/tanki:windows

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: uv sync --all-extras

      - name: build for macos
        run: uv run poe build-macos

      - name: rename out dir
        run: mv build/macos/thetanki build/macos/tanki-macos

      # - name: make archive
      #   run: |
      #     pushd build/macos
      #     tar cvfz tanki-macos.tar.gz thetanki
      #     ls -lah tanki-macos.tar.gz
      #     popd

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: tanki-macos-${{ github.sha }}.tar.gz
      #     path: build/macos/tanki-macos.tar.gz

      - name: upload release to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: macos
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default
          unzip butler.zip && chmod +x butler
          ./butler push build/macos/ pkulev/tanki:${CHANNEL}
